version: '2.0'
version: '3.3'

services:

  sample:
    container_name: sdg-react_app
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '3001:3000'
    environment:
      - NODE_ENV=development